name: VPN_Collector
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Configs
        run: |
          # Используем альтернативный стабильный источник
          curl -L https://raw.githubusercontent.com/moseparsi/proxy-grabber/main/sub/base64/mix -o subscription.txt
          
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git add subscription.txt
          git commit -m "update with stable source" || exit 0
          git push
